export const LOADING = "LOADING";
export const FETCH_ASTEROIDS_SUCCESS = "FETCH_ASTEROIDS_SUCCESS";
export const FETCH_ASTEROIDS_ERROR = "FETCH_ASTEROIDS_ERROR";
export const GET_ASTEROID_DATA = "GET_ASTEROID_DATA";